http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  api:
    host: 'localhost'
    paths: /serivceA
serviceEndpoints:
  serviceA:
    url: 'http://localhost:4567/hello'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  basic:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: serviceA
              changeOrigin: false
